In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


## Introduction to tensors

### Creating tensors
PyTorch tensors are ceating usng `torch.Tensor()`

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [13]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
TENSOR[0][0]

tensor([1, 2, 3])

In [18]:
## NEW TENSOR
TENSOR_NEW = torch.tensor([[[34,5,20],[9,0,7],[33,34,6]]])
TENSOR_NEW.ndim

3

In [19]:
TENSOR_NEW.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR_NEW[0][0]

tensor([34,  5, 20])

### Random Tensors

Why random tensors?
Random tensors are imporant because the way many neural networks learn is they start with tensors full of rnadom #s and then ajudst to better represent the data.

`Start with random numbers -> look at data -> update random #s -> look at data -> update`

In [21]:
## create a random tensor of size/shahpe (3,4)
random_tensor = torch.rand(5,4)
random_tensor

tensor([[0.7966, 0.9725, 0.0330, 0.9777],
        [0.1238, 0.9956, 0.6226, 0.5850],
        [0.5500, 0.7213, 0.6265, 0.6902],
        [0.7588, 0.4021, 0.1306, 0.5271],
        [0.7282, 0.6211, 0.2450, 0.3887]])

In [22]:
random_tensor

tensor([[0.7966, 0.9725, 0.0330, 0.9777],
        [0.1238, 0.9956, 0.6226, 0.5850],
        [0.5500, 0.7213, 0.6265, 0.6902],
        [0.7588, 0.4021, 0.1306, 0.5271],
        [0.7282, 0.6211, 0.2450, 0.3887]])

In [23]:
random_tensor = torch.rand(5,4)
random_tensor.ndim

2

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels (RBG)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
random_tensor = torch.rand(5,10,10)
random_tensor.ndim, random_tensor.shape

(3, torch.Size([5, 10, 10]))

### Zeroes and ones

In [26]:
# create a tensor of all zeoros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [30]:
# use torch.arange()
# torch.range deprecated
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
## Creating tensors like
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
ten_zeros = torch.zeros_like(input=one_to_ten)

In [33]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note** Tensor datatypes is one of the 3 big building blocks/potential sources of errors with PyTorch and deep learning;
1. Need the right datatype to perform certain operations
2. Need the right shape of the data
3. Tensor needs to be on the appropriate/right device

In [34]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [35]:
# default data type to come out as float 32
float_32_tensor.dtype

torch.float32

In [36]:
# Float 32 tensor
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what type of unit the data is - 16 bit, 32 bit vs 64 bit
                               device=None, # what device the tensor is on; ex: 'cuda', etc
                               requires_grad=False) # if want PyTorch to track the gradients of a tensor

In [38]:
float_32_tensor.dtype

torch.float32

In [39]:
# converting from float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [40]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [41]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from Tensors - tensor Attributes
1. Tensor datatype - can use `tensor.dtype`
2. Tensor shape - can use `tensor.shape`
3. Tensor device - can use `tensor.device`

In [43]:
# create a tesnor
some_tensor = torch.rand(10,7)
some_tensor

tensor([[0.6069, 0.2954, 0.9541, 0.0475, 0.7120, 0.3352, 0.2747],
        [0.3852, 0.7632, 0.8614, 0.9106, 0.2425, 0.3085, 0.5750],
        [0.7059, 0.1973, 0.3854, 0.3412, 0.3631, 0.3436, 0.9649],
        [0.0964, 0.5626, 0.1305, 0.9319, 0.6145, 0.3053, 0.0333],
        [0.8197, 0.8515, 0.1431, 0.5747, 0.7330, 0.8209, 0.2758],
        [0.8668, 0.0964, 0.7762, 0.8798, 0.0064, 0.2053, 0.4832],
        [0.7815, 0.3578, 0.0564, 0.5585, 0.7043, 0.1642, 0.0866],
        [0.8631, 0.3916, 0.7764, 0.7561, 0.5120, 0.5158, 0.2252],
        [0.8627, 0.5863, 0.9137, 0.2304, 0.5714, 0.7116, 0.6934],
        [0.4611, 0.0447, 0.2468, 0.6002, 0.2563, 0.8688, 0.3348]])

In [44]:
# find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Tensor is on device: {some_tensor.device}")

tensor([[0.6069, 0.2954, 0.9541, 0.0475, 0.7120, 0.3352, 0.2747],
        [0.3852, 0.7632, 0.8614, 0.9106, 0.2425, 0.3085, 0.5750],
        [0.7059, 0.1973, 0.3854, 0.3412, 0.3631, 0.3436, 0.9649],
        [0.0964, 0.5626, 0.1305, 0.9319, 0.6145, 0.3053, 0.0333],
        [0.8197, 0.8515, 0.1431, 0.5747, 0.7330, 0.8209, 0.2758],
        [0.8668, 0.0964, 0.7762, 0.8798, 0.0064, 0.2053, 0.4832],
        [0.7815, 0.3578, 0.0564, 0.5585, 0.7043, 0.1642, 0.0866],
        [0.8631, 0.3916, 0.7764, 0.7561, 0.5120, 0.5158, 0.2252],
        [0.8627, 0.5863, 0.9137, 0.2304, 0.5714, 0.7116, 0.6934],
        [0.4611, 0.0447, 0.2468, 0.6002, 0.2563, 0.8688, 0.3348]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([10, 7])
Tensor is on device: cpu


### Manipulating tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [45]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor +10

tensor([11, 12, 13])

In [46]:
## multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [47]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [48]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of performing multiplication in neural nets and deep learning

1. Element-wise multiplication
2.  Matrix multiplication (aka dot product)

In [49]:
## Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [50]:
## Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Matrix multiplication by hand
(1*1) + (2*2) + (3*3)

14

In [52]:
%%time 
value=0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]
value ## 1.77 milliseconds

CPU times: user 1.03 ms, sys: 897 µs, total: 1.93 ms
Wall time: 1.94 ms


tensor(14)

In [53]:
%%time
torch.matmul(tensor, tensor) ## 589 micro-seconds
# also can use `@` for matrix multiplication

CPU times: user 72 µs, sys: 4 µs, total: 76 µs
Wall time: 48.2 µs


tensor(14)

### Matrix Multiplication - Two Main Rules

One of the most common errors in deep learning is shape error

**`Rule 1`**: The **inner dimensions** must match
* `(3,2) @ (3,2)` - won't work
* `(2,3) @ (3,2)` - will work
* `(3, 2) @ (2,3)` - will work
  
**`Rule 2`**: The resulting matrix has a shape of the **outer dimensions**
* `(2,3) @ (3,2)` -> `(2,2)`
*  `3,2 @ (2,3)` -> `(3,3)`

In [54]:
torch.rand(3,2).shape

torch.Size([3, 2])

In [55]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.3357, 0.6320, 0.3440],
        [0.1770, 0.3743, 0.1564],
        [0.4238, 0.8495, 0.4030]])

In [56]:
torch.matmul(torch.rand(10,10), torch.rand(10,10)).shape

torch.Size([10, 10])

`[2:35]`

### One of the most common errors in deep learning: shape errors

In [57]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [58]:
'http://matrixmultiplication.xyz/'

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix tensor shape issues:
+ check this out == 'http://matrixmultiplication.xyz/'
+ can manipulate the shape of one of the tensors using tranpose
+ A **`transpose`** switches the axes of dimensions of a given tensor

In [59]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [60]:
# implement T
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [61]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [62]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [63]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [64]:
# the matrix multiplication operation works
# when tensor is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_b = {tensor_B.shape}")
print(f"\nNew shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"\nMultiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_b = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


---

### Finding the min, max, mean and sum [Tensor Aggregration]

In [65]:
# create a tensor
x = torch.arange(0,101,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [66]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [67]:
# find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [68]:
# find the mean
# torch.mean requires a tensor of float32 to work
torch.mean(x.type(torch.float32))

tensor(50.)

In [69]:
# find the mean
x.type(torch.float32).mean()

tensor(50.)

In [70]:
# find the sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

#### Finding the positional min and max

In [71]:
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [72]:
# find the position in tensor with min value
x.argmin(), x[0]

(tensor(0), tensor(0))

In [73]:
# find the position in tensor with max value
x.argmax(), x[10]

(tensor(10), tensor(100))

### Reshaping, viewing and stacking, squeezing and unsqueezing
+ Reshaping - reshapes an input tensor to a defined shape
+ View - Return a view of an input tensor of certain shape but keep the same memory as original tensor
+ Stacking - combine multiple tensors on top (vstack), or side by side (hstack)
+ Squeezing - removes all `1` dimensions from a tensor
+ Unsqueeze - add a `1` dimension
+ Permute - return a view of the input with dimensions permuted in a certain way

In [74]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

#### Reshaping

In [75]:
# add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [76]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

#### View

In [77]:
# change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [78]:
# changing z changes x (becuse a view or a tenor shares the same memory)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

#### Stack tensors on top of each other

In [79]:
#dimensions=0
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [80]:
# dim =1
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

#### Squeeze, unsqueeze

In [81]:
# torch.squeeze (removes all single dimensions from a target tensor)
x = torch.zeros(2,1,2,1,2)
x.size()
y = torch.squeeze(x)
y.size()
y=torch.squeeze(x,0)
y.size()
y=torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [82]:
x_reshaped.shape, x_reshaped.dim()

(torch.Size([9, 1]), 2)

In [83]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [84]:
x_reshaped.squeeze().shape, x_reshaped.squeeze().dim()

(torch.Size([9]), 1)

In [85]:
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [86]:
# torch.unsqueeze() - add a single dimension to target tesnor at specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape: torch.Size([1, 9])


In [87]:
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add an extra dimension
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New Tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new shape: torch.Size([9, 1])


#### Permute
+ returns a view of the original tensor with reshaped dimensions 

In [88]:
x_original = torch.rand(size=(224,224,3)) # height, width, color channel of image

# permute the original tensor to reannrage the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, and 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [91]:
x_original[0,0,0] = 78218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(78218.), tensor(78218.))

#### Indexing (selecting data from tensors)

In [2]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [3]:
# index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# index no middle bracket
x[0][1]

tensor([4, 5, 6])

In [98]:
x[0,1]

tensor([4, 5, 6])

In [107]:
# index on the most inner bracket (last dimension)
x[0,1,1]

tensor(5)

In [108]:
x[0,2,2]

tensor(9)

In [109]:
# can also sue the ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [110]:
# get all values of 0th and 1st dimensions but ony index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [112]:
# get all values of the 0 dimension but only the 1 index value of 1 and 2
x[:, 1, 1:2]

tensor([[5]])

In [113]:
# get index 0 of 0th nd 1st dimension and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

In [5]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [6]:
# index on x to return 3, 6, 9
x[:,:,2]

tensor([[3, 6, 9]])

#### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library with fucntionality to interact
+Can change from data in NumPy to a Torch tensor
+ PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [11]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [12]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [13]:
# change the value of array - what will it do to `tensor`
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [14]:
# Tensor uo NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [15]:
# change the tensor, what happens to `numpy_tensor`
tensor = tensor +1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#### Reproducibility - taking the random out of random

+ In short, a neural net learns by starting with random numbers - > perform tensor operations -> update random numbers to better reflect the numbers/data
+ To reduce the randomness for neural nets comes the concept of a `random seed`.
+ What the random seed does is 'flavor' the randomness

In [17]:
torch.rand(3,3) # random #s every single time

tensor([[0.5129, 0.8009, 0.2816],
        [0.1626, 0.2357, 0.1348],
        [0.8314, 0.5502, 0.0405]])

In [18]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8012, 0.5115, 0.7311, 0.8516],
        [0.2778, 0.7239, 0.6151, 0.4462],
        [0.0113, 0.4933, 0.0973, 0.8319]])
tensor([[0.2991, 0.0749, 0.1459, 0.9224],
        [0.6752, 0.1584, 0.4318, 0.5010],
        [0.3136, 0.1715, 0.8901, 0.8849]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [20]:
# let's make some random but reproducible tensors
# set the random seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) ## need to specify a 2nd time if calling random seed on anohter
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


#### Running tesnors an PyTorch objects on GPUs
+ GPU = faster computaiton on numbers